language: android
sudo: false
jdk: oraclejdk8

env:
  # TODO UI test on CI
  #matrix:
  #- ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
  #- ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
  global:
  - ANDROID_API=27
  - EMULATOR_API=27
  - ADB_INSTALL_TIMEOUT=30 # minutes
  - secure: "myQmH/Qymtwh8VcXWkNC6z9x1n1GQ9DAdXa569oPcRF+vCFOhM7bGldNvQ5hPtfO8Qb/B0fmvqntoTIMyFm1JH7yPV7Bp8VsxHLlWgEIAb3ZpZgwN/0mGMaZ5+oBE+jNq2wwFV20C9CB/WoSJofsVx9fRKUJWqbfa5Ge/WnYygchmqML/WsRPl9hHggc8SUj3MUEYa2wdYSpby7+3knZ8b2aLh4Sdjd9AeWO4GXpwZpnqZJn2hgyqZSLcmlGnK+LUfpQ9KASsFkmx8PHG8/ic/qoPhPN++AAbCPYlP4RwnsK3sHBSyNex7aHrwrlxlJbkebxhYUJpU0SCZrSrR4o+OxeAkPCeJ3JkA9KEQa9hHAwNPNgb65+L5lc2V7I6P1Ur2FCI59h9ZqCCUBUsqmY6zk8V2U6CzhLTvm9CQpu+kxZbTq/hRryjMgE6r4qzRWLd9J1dOyddaKpVQn7iFvAaIUkXnvW87BZqnVdhJMsFUgFws3FcneC2ekUrENveBEI2ty/8IagyCG70O2bvr6xCZmrlZzUH0cqtPWDgDlsBqdF9OdqqU2d9cQugnOV74Qmhqr8PmvuSIVYEi+I1/uZOkMYMTTuiGD6bumyFI9ADrO/YfDR6vJNgC8lmd7kYJBV8rz30Z6p6nbZcR+8HB5uhnBCGfNdfBYUyiqTrM1pTgo="
  - secure: "YM1UDsrdpMYjEVne39/RhltmXoqb0OxPpb9fJUmCIpE4OQ+YIGK51L7Q+zC8A2maGCsT0FMwAdgBT7fIBNejIJhvMp1a4qqRsBoA1jESVd2+8FrOwYmzvHagh1QPXyrMBPtpK2PRNomw2letW1ZNlCSJjQK1YsIrBwdGg2yq4IDnC6vE0II19V0Z+8UEluVy91f5IcNrBdUcLWQB+vwefvcskVIiSeotadqHqcW9D1A07WPHC7tFi3Mk508O1Woj3HZBbbgHbOgM9pQCMdl0HhZWCO9e73nxxKiXHhGDnBoAnvU1SDlZ3WJ56GHuZ/8rCkq7V9trwKh/0dWGyZAaOFqqCfEW8YJTVn8x8azRK9RdlbDeaCRsXfNzhbI0sNH8sU/TFnf2+GHIHzoe4PXtVoUnfESh37eEeEfZCs2lH0oF/sMqIQ5DQj1v4bA/T6OhqlukINl0V7o+KH/AV1JL7lvzkmEyIXM2f7aZqPjOlwUw/6IyBITjygIxei4KKTwse79uFoQ0XCm8twX+ExdZh+M8AkPyOdsOFM2ExDnGrm32OzngzKyvXaKr2Cs/ah+zWx+1hgg8z9NVoyVWyKEre4eIqVkrBeHFa/8nwQVrKVkF+MsKduTn6gB9DZcDsk9xRvLVAJpwCrpMM1cMDfeV/0gcZB0m30qt74P8QfMz/+w="

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper/

android:
  components:
  - tools-27.0.3
  - platform-tools-27-0.3
  - build-tools-27.0.3
  - android-27
  - add-on
  - extra
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_444afb1c160d_key -iv $encrypted_444afb1c160d_iv -in sec.tar.enc -out sec.tar -d
  - tar xvf sec.tar
  - mv google-services.json app/google-services.json && mv props.gradle app/props.gradle
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

before_script:
  #Grant permissions
  - chmod +x gradlew
  - echo "y" | android update sdk -a --no-ui --filter android-27
  - $ANDROID_HOME/tools/bin/sdkmanager tools
  # Print tools info
  - cat $ANDROID_HOME/platform-tools/source.properties | grep Pkg.Revision
  - cat $ANDROID_HOME/tools/source.properties | grep Pkg.Revision
  # TODO run UI test on CI
  #- sdkmanager "system-images;$ANDROID_TARGET;google_apis;$ANDROID_ABI"
  #- echo no | $ANDROID_HOME/tools/bin/avdmanager create avd -n test -k "system-images;$ANDROID_TARGET;google_apis;$ANDROID_ABI"
  #- $ANDROID_HOME/tools/emulator -avd test -no-skin -no-window &    #Start emulator
  #- android-wait-for-emulator
  #- adb shell input keyevent 82 &

script:
  - "./gradlew ktlint clean build jacocoTestReport jacocoDomainTestReport -PdisablePreDex --stacktrace"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - cp $TRAVIS_BUILD_DIR/mnmaolvdprod.keystore $HOME/mnmaolvdprod.keystore
  - cd app/build/outputs/apk/prod/release
  - ls
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/mnmaolvdprod.keystore -storepass $storepass -keypass $keypass app-prod-release-unsigned.apk production
  # Verification
  - jarsigner -verify app-prod-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/27.0.3/zipalign -v 4 app-prod-release-unsigned.apk aolvmeneame.apk"

deploy:
  provider: releases
  file: aolvmeneame.apk
  skip_cleanup: true
  overwrite: true
  on:
    repo: aolivafaura/meneameapp
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "LTaz8+md1HZWusW4NxZCtWnOfvKo7gDxQMXOJKc8ORgX8onWJrW+7muxo0ci/Br8Rw60A/VCmhZ6gpQWwLSKWjrX7+V/45kpXrUXY6TWf4FDc832ji9d+UrSDF9hStaYitV5707VwWNvlxvw9nRmvh0LrLjFGa9O22c5DnWfGBiPdy6ieygOYPeKBPZhDl9TDeng7lPSxx+aq5II50okM/QFLZxNekEuXNmJRWjBXgvC4fv170+e0am3uHmCdMouOhgJKOgfQog6tTJOSVgsou64Nnl1OZ37T07prKzkY2Y3O+G9hDj5QEPO8oalL0JhSqDgvxh8ncO9Dg2376orj5QaGsIpYzzYAyjblr3bIT1pu9iD/FXkBaRBTtPUvciqNrKJDlXJHYbZB2soCCxX3z5mF9pGXR7tdrsAJfT+6HS/DlWQWA5AVQTeOiwAUp1ukxu6Ld0JTiKzZPKhot+tem1gih3O7H1qPcan9LooPlNUd+opBhJazXK/Oj9GAAsvzSSOIQ69KeLWMDl4R93bYTnxRyaKTihj3auCnFlB3EAzI9WPhdd6btxOBLaeVrgAa0bLDH2YC9/PKg5WcKzkusUWmrS1wPtrJC/SZwKo52AjSuTcu7TEpB36tAqRanYzUegoN6Bhy1CukE8VmbnkDold7xLMOS/qe37CdytlUek="
