language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=30 # minutes
  - ANDROID_HOME=$HOME/android-sdk

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    # Dependencies
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper/
    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

before_install:
  - openssl aes-256-cbc -K $encrypted_0b308b3bfcfe_key -iv $encrypted_0b308b3bfcfe_iv -in sec.tar.gz.enc -out sec.tar.gz -d
  - tar -xzvf sec.tar.gz
  - mv google-services.json app/google-services.json
  - mv group_aliases.txt app/group_aliases.txt
  - mv fabric.properties app/fabric.properties
  - mv signing.properties app/signing.properties
  - mv mnmaolvdprod.keystore app/mnmaolvdprod.keystore
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  # Latest version available here: https://developer.android.com/studio/index.html#downloads
  - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
  - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager tools > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager platform-tools > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-${ANDROID_API}" > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "extras;google;m2repository" > /dev/null

jobs:
  include:
    - stage: test
      script:
        - "./gradlew ktlint --stacktrace"
      script:
        - "./gradlew jacocoTestReport jacocoDomainTestReport --stacktrace"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      if: tag IS present
      script: >
              ./gradlew assembleProdRelease -PdisablePreDex --stacktrace
              && ./gradlew crashlyticsUploadDistributionProdRelease --stacktrace
