language: android
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.3
  - ADB_INSTALL_TIMEOUT=30 # minutes
  - ANDROID_HOME=$HOME/android-sdk
  - secure: "myQmH/Qymtwh8VcXWkNC6z9x1n1GQ9DAdXa569oPcRF+vCFOhM7bGldNvQ5hPtfO8Qb/B0fmvqntoTIMyFm1JH7yPV7Bp8VsxHLlWgEIAb3ZpZgwN/0mGMaZ5+oBE+jNq2wwFV20C9CB/WoSJofsVx9fRKUJWqbfa5Ge/WnYygchmqML/WsRPl9hHggc8SUj3MUEYa2wdYSpby7+3knZ8b2aLh4Sdjd9AeWO4GXpwZpnqZJn2hgyqZSLcmlGnK+LUfpQ9KASsFkmx8PHG8/ic/qoPhPN++AAbCPYlP4RwnsK3sHBSyNex7aHrwrlxlJbkebxhYUJpU0SCZrSrR4o+OxeAkPCeJ3JkA9KEQa9hHAwNPNgb65+L5lc2V7I6P1Ur2FCI59h9ZqCCUBUsqmY6zk8V2U6CzhLTvm9CQpu+kxZbTq/hRryjMgE6r4qzRWLd9J1dOyddaKpVQn7iFvAaIUkXnvW87BZqnVdhJMsFUgFws3FcneC2ekUrENveBEI2ty/8IagyCG70O2bvr6xCZmrlZzUH0cqtPWDgDlsBqdF9OdqqU2d9cQugnOV74Qmhqr8PmvuSIVYEi+I1/uZOkMYMTTuiGD6bumyFI9ADrO/YfDR6vJNgC8lmd7kYJBV8rz30Z6p6nbZcR+8HB5uhnBCGfNdfBYUyiqTrM1pTgo="
  - secure: "YM1UDsrdpMYjEVne39/RhltmXoqb0OxPpb9fJUmCIpE4OQ+YIGK51L7Q+zC8A2maGCsT0FMwAdgBT7fIBNejIJhvMp1a4qqRsBoA1jESVd2+8FrOwYmzvHagh1QPXyrMBPtpK2PRNomw2letW1ZNlCSJjQK1YsIrBwdGg2yq4IDnC6vE0II19V0Z+8UEluVy91f5IcNrBdUcLWQB+vwefvcskVIiSeotadqHqcW9D1A07WPHC7tFi3Mk508O1Woj3HZBbbgHbOgM9pQCMdl0HhZWCO9e73nxxKiXHhGDnBoAnvU1SDlZ3WJ56GHuZ/8rCkq7V9trwKh/0dWGyZAaOFqqCfEW8YJTVn8x8azRK9RdlbDeaCRsXfNzhbI0sNH8sU/TFnf2+GHIHzoe4PXtVoUnfESh37eEeEfZCs2lH0oF/sMqIQ5DQj1v4bA/T6OhqlukINl0V7o+KH/AV1JL7lvzkmEyIXM2f7aZqPjOlwUw/6IyBITjygIxei4KKTwse79uFoQ0XCm8twX+ExdZh+M8AkPyOdsOFM2ExDnGrm32OzngzKyvXaKr2Cs/ah+zWx+1hgg8z9NVoyVWyKEre4eIqVkrBeHFa/8nwQVrKVkF+MsKduTn6gB9DZcDsk9xRvLVAJpwCrpMM1cMDfeV/0gcZB0m30qt74P8QfMz/+w="

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    # Dependencies
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper/
    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

before_install:
  - openssl aes-256-cbc -K $encrypted_aee72d1c3958_key -iv $encrypted_aee72d1c3958_iv -in sec.tar.enc -out sec.tar -d
  - tar xvf sec.tar
  - mv google-services.json app/google-services.json && mv props.gradle app/props.gradle && mv fabric.properties app/fabric.properties
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  # Latest version available here: https://developer.android.com/studio/index.html#downloads
  - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
  - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager tools > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager platform-tools > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-${ANDROID_API}" > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager "extras;google;m2repository" > /dev/null

jobs:
  include:
    - stage: test
      script:
        - "./gradlew ktlint --stacktrace"
      script:
        - "./gradlew jacocoTestReport jacocoDomainTestReport --stacktrace"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      if: tag IS present
      script: >
              ./gradlew assembleProdRelease -PdisablePreDex --stacktrace
              && cp ${TRAVIS_BUILD_DIR}/mnmaolvdprod.keystore ${HOME}/mnmaolvdprod.keystore
              && cd app/build/outputs/apk/prod/release
              && jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${HOME}/mnmaolvdprod.keystore -storepass $storepass -keypass $keypass app-prod-release-unsigned.apk production
              && jarsigner -verify app-prod-release-unsigned.apk
              && ${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-prod-release-unsigned.apk aolvmeneame.apk
              && cd ${TRAVIS_BUILD_DIR}
              && ./gradlew crashlyticsUploadDistributionProdRelease
